version: '2'

services:
  jetson-app:
    build: ./jetson_nano
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - FAN_PERCENT=50
    restart: unless-stopped
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'